INSERT INTO ITEM (NAME, PRICE, QTY, DELETED) VALUES ('Pen', 5, 5, false);
INSERT INTO ITEM (NAME, PRICE, QTY, DELETED) VALUES ('Book', 10, 10, false);
INSERT INTO ITEM (NAME, PRICE, QTY, DELETED) VALUES ('Bag', 30, 30, false);
INSERT INTO ITEM (NAME, PRICE, QTY, DELETED) VALUES ('Pencil', 3, 10, false);
INSERT INTO ITEM (NAME, PRICE, QTY, DELETED) VALUES ('Shoe', 45, 55, false);
INSERT INTO ITEM (NAME, PRICE, QTY, DELETED) VALUES ('Box', 5, 5, false);
INSERT INTO ITEM (NAME, PRICE, QTY, DELETED) VALUES ('Cap', 25, 25, false);


INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE, DELETED) VALUES (1, 5, 'T', false);
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE, DELETED) VALUES (2, 10, 'T', false);
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE, DELETED) VALUES (3, 30, 'T', false);
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE, DELETED) VALUES (4, 3, 'T', false);
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE, DELETED) VALUES (5, 45, 'T', false);
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE, DELETED) VALUES (6, 5, 'T', false);
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE, DELETED) VALUES (7, 25, 'T', false);
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE, DELETED) VALUES (4, 7, 'T', false);
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE, DELETED) VALUES (5, 10, 'W', false);