INSERT INTO ITEM (NAME, PRICE, QTY) VALUES ('Pen', 5, 5);
INSERT INTO ITEM (NAME, PRICE, QTY) VALUES ('Book', 10, 10);
INSERT INTO ITEM (NAME, PRICE, QTY) VALUES ('Bag', 30, 30);
INSERT INTO ITEM (NAME, PRICE, QTY) VALUES ('Pencil', 3, 10);
INSERT INTO ITEM (NAME, PRICE, QTY) VALUES ('Shoe', 45, 55);
INSERT INTO ITEM (NAME, PRICE, QTY) VALUES ('Box', 5, 5);
INSERT INTO ITEM (NAME, PRICE, QTY) VALUES ('Cap', 25, 25);


INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (1, 5, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (2, 10, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (3, 30, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (4, 3, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (5, 45, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (6, 5, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (7, 25, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (4, 7, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (5, 10, 'W');